# -*- coding: utf-8 -*-
"""化工廠.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKnC51fachi1hmtE7rx8MrgJF0Xbfl2P
"""

pip install pandas numpy torch gymnasium stable-baselines3 scikit-learn sympy==1.12

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3 import PPO
from sklearn.preprocessing import StandardScaler
import warnings

warnings.filterwarnings('ignore')

# ==========================================
# 1. 資料載入與前處理
# ==========================================
def load_and_preprocess_data(csv_path):
    print(">>> [1/4] 載入並處理歷史資料...")
    df = pd.read_csv(csv_path)
    df = df[df['arm'] == 'Legacy_2passRO_MB'].reset_index(drop=True)

    features = [
        'feed_SDI', 'feed_conductivity_uScm', 'resistivity_MOhm_cm',
        'TOC_ppb', 'cation_leak_ppb', 'anion_leak_ppb', 'deltaP_bar'
    ]

    df['action'] = df['MB_regen'].apply(lambda x: 1.0 if x == 'Yes' else 0.0)
    df[features] = df[features].fillna(method='ffill').fillna(0)

    scaler = StandardScaler()
    scaled_states = scaler.fit_transform(df[features])
    actions = df['action'].values.reshape(-1, 1)

    X, Y = [], []
    for i in range(len(scaled_states) - 1):
        x_combined = np.concatenate([scaled_states[i], actions[i]])
        X.append(x_combined)
        Y.append(scaled_states[i+1])

    X = torch.FloatTensor(np.array(X)).unsqueeze(1)
    Y = torch.FloatTensor(np.array(Y))

    return X, Y, scaled_states, scaler, features

# ==========================================
# 2. 建立 PINN (物理驅動神經網路) 模型
# ==========================================
class UPW_PINN_LSTM(nn.Module):
    def __init__(self, input_dim, output_dim, hidden_dim=64):
        super(UPW_PINN_LSTM, self).__init__()
        self.lstm = nn.LSTM(input_size=input_dim, hidden_size=hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x, hidden=None):
        out, hidden = self.lstm(x, hidden)
        delta_state = self.fc(out[:, -1, :])
        current_state = x[:, -1, :-1]
        next_state = current_state + delta_state
        return next_state, delta_state, hidden

def train_pinn_twin(X, Y, state_dim, action_dim, toc_idx, epochs=250):
    print(">>> [2/4] 訓練 PINN 數位分身模型 (融合數據與物理法則)...")
    model = UPW_PINN_LSTM(input_dim=state_dim + action_dim, output_dim=state_dim)
    optimizer = optim.Adam(model.parameters(), lr=0.003)
    mse_criterion = nn.MSELoss()

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()

        next_state_pred, delta_state_pred, _ = model(X)
        actions = X[:, 0, -1]
        delta_toc = delta_state_pred[:, toc_idx]

        # ------------------------------------------------
        # 🌟 PINN 核心：加上「物理速限」的混合損失函數
        # ------------------------------------------------
        loss_data = mse_criterion(next_state_pred, Y)

        # 規則 A1: 若沒保養 (action=0)，TOC 絕對不能減少
        penalty_no_maint_min = torch.clamp(-delta_toc, min=0.0) * (1 - actions)

        # 🚀 [新增防暴衝機制] 規則 A2: 若沒保養，TOC 每週最多只能增加 0.4 ppb
        penalty_no_maint_max = torch.clamp(delta_toc - 0.4, min=0.0) * (1 - actions)

        # 規則 B: 若保養 (action=1)，TOC 必須大幅下降 (至少降 1.5 ppb)
        penalty_maint = torch.clamp(delta_toc + 1.5, min=0.0) * actions

        # 給予物理法則極高權重 (10.0)，確保網路不會因為 historical data 偏高而暴衝
        loss_physics = 10.0 * torch.mean(penalty_no_maint_min + penalty_no_maint_max + penalty_maint)

        total_loss = loss_data + loss_physics
        total_loss.backward()
        optimizer.step()

        if (epoch+1) % 50 == 0:
            print(f"    PINN Epoch [{epoch+1:3d}/{epochs}] | 總Loss: {total_loss.item():.4f} (Physics: {loss_physics.item():.4f})")

    return model

# ==========================================
# 3. 強化學習模擬環境 (PINN 驅動)
# ==========================================
class PINNSimulatedUPWEnv(gym.Env):
    def __init__(self, pinn_model, initial_states, scaler, feature_names):
        super(PINNSimulatedUPWEnv, self).__init__()
        self.pinn_model = pinn_model
        self.pinn_model.eval()
        self.initial_states = initial_states
        self.scaler = scaler
        self.feature_names = feature_names

        self.state_dim = len(feature_names)
        self.action_space = spaces.Discrete(2)
        self.observation_space = spaces.Box(low=-10.0, high=10.0, shape=(self.state_dim,), dtype=np.float32)

        self.toc_idx = feature_names.index('TOC_ppb')
        self.step_count = 0
        self.max_steps = 52
        self.consecutive_no_maintenance = 0

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.step_count = 0
        self.consecutive_no_maintenance = 0

        idx = np.random.randint(0, len(self.initial_states))
        self.current_state = self.initial_states[idx].astype(np.float32)

        real_state = self.scaler.inverse_transform([self.current_state])[0]
        real_state[self.toc_idx] = 2.0  # 健康起點
        self.current_state = self.scaler.transform([real_state])[0].astype(np.float32)

        self.hidden_state = (
            torch.zeros(1, 1, self.pinn_model.lstm.hidden_size),
            torch.zeros(1, 1, self.pinn_model.lstm.hidden_size)
        )
        return self.current_state, {}

    def step(self, action):
        self.step_count += 1

        action_arr = np.array([action], dtype=np.float32)
        pinn_input = np.concatenate([self.current_state, action_arr])
        pinn_input_tensor = torch.FloatTensor(pinn_input).view(1, 1, -1)

        with torch.no_grad():
            next_state_tensor, _, self.hidden_state = self.pinn_model(pinn_input_tensor, self.hidden_state)

        self.current_state = next_state_tensor.numpy().flatten()
        real_state = self.scaler.inverse_transform([self.current_state])[0]
        real_toc = real_state[self.toc_idx]

        # 避免保養後數值無限制變負的底線保護
        if real_toc < 1.0: real_toc = 1.0
        real_state[self.toc_idx] = real_toc
        self.current_state = self.scaler.transform([real_state])[0].astype(np.float32)

        weeks_without_maint = self.consecutive_no_maintenance
        if action == 0:
            self.consecutive_no_maintenance += 1
        else:
            self.consecutive_no_maintenance = 0

        # --- 獎勵函數 ---
        reward = 1.0
        done = False

        if real_toc > 5.0:
            reward -= 100
            done = True
        elif real_toc > 4.0:
            reward -= 10  # 這一次 AI 會有充分的時間停留在 4.x 收到警告！

        if action == 1:
            reward -= 15

        if self.step_count >= self.max_steps:
            done = True

        info = {'real_toc': real_toc, 'no_maint_weeks': weeks_without_maint}
        return self.current_state, float(reward), done, False, info

# ==========================================
# 4. 主程式
# ==========================================
if __name__ == "__main__":
    CSV_PATH = "/content/UPW專案_100rows.csv"

    try:
        X, Y, scaled_states, scaler, feature_names = load_and_preprocess_data(CSV_PATH)
        state_dim = scaled_states.shape[1]
        toc_idx = feature_names.index('TOC_ppb')

        pinn_model = train_pinn_twin(X, Y, state_dim=state_dim, action_dim=1, toc_idx=toc_idx, epochs=250)

        print(">>> [3/4] 初始化強化學習環境 (由具備老化速限的 PINN 完全接管)...")
        env = PINNSimulatedUPWEnv(pinn_model=pinn_model, initial_states=scaled_states,
                                  scaler=scaler, feature_names=feature_names)

        print(">>> [4/4] 訓練 PPO 強化學習代理人 (AI 學習中，請稍候)...")
        # 將步數稍微提高到 40000 確保 PPO 能收斂
        rl_agent = PPO("MlpPolicy", env, verbose=0, learning_rate=0.0005)
        rl_agent.learn(total_timesteps=40000)

        print("\n==========================================")
        print("🎉 PINN 架構訓練完成！模擬 AI 一年的維護決策")
        print("==========================================")

        obs, info = env.reset()
        done = False
        schedule = []

        while not done:
            action, _states = rl_agent.predict(obs, deterministic=True)
            obs, reward, done, truncated, info = env.step(action)

            step_num = env.step_count
            real_toc = info['real_toc']
            no_maint = info['no_maint_weeks']

            if action == 1:
                schedule.append(step_num)
                print(f"👉 [第 {step_num:2d} 週] ⚠️ PINN 預測水質將惡化 | AI 主動執行 MB 再生！ (距上次保養 {no_maint} 週，洗後降至 {real_toc:.2f} ppb)")
            else:
                print(f"   [第 {step_num:2d} 週] 💧 TOC={real_toc:.2f} ppb | 正常產水")

        print("------------------------------------------")
        print(f"📊 全年總維護次數: {len(schedule)} 次")
        print(f"📅 維護發生在第幾週: {schedule}")

    except FileNotFoundError:
        print(f"❌ 錯誤：找不到 '{CSV_PATH}'，請確認檔案位置。")